### ISSUE TITLE
农历月及朔的手表时 前后年份相邻的月不一致

### ISSUE THREAD

**Issue by yidao2015** [Comee/SolarTerms24#2]
如：2017 年末的大雪冬至后面跟的农历月 与 2018年始 的大雪冬至后跟的农历月 不一致。
paiYue(2017)
节气  手表时              中气  手表时              农历月  朔的手表时
大雪: 2016-12-07 00:41:03 冬至: 2016-12-21 18:44:07 12月大: 2016-12-29 14:53:15
小寒: 2017-01-05 11:55:40 大寒: 2017-01-20 05:23:36 正月小: 2017-01-28 08:07:10
立春: 2017-02-03 23:34:04 雨水: 2017-02-18 19:31:24 二月大: 2017-02-26 22:58:28
惊蛰: 2017-03-05 17:32:46 春分: 2017-03-20 18:28:38 三月小: 2017-03-28 10:57:18
清明: 2017-04-04 22:17:14 谷雨: 2017-04-20 05:26:53 四月大: 2017-04-26 20:16:13
立夏: 2017-05-05 15:30:56 小满: 2017-05-21 04:30:48 五月小: 2017-05-26 03:44:34
芒种: 2017-06-05 19:36:33 夏至: 2017-06-21 12:24:02 六月小: 2017-06-24 10:30:48
小暑: 2017-07-07 05:50:38 大暑: 2017-07-22 23:15:18 六闰大: 2017-07-23 17:45:34
立秋: 2017-08-07 15:39:58 处暑: 2017-08-23 06:20:12 七月小: 2017-08-22 02:30:07
白露: 2017-09-07 18:38:35 秋分: 2017-09-23 04:01:48 八月大: 2017-09-20 13:29:49
寒露: 2017-10-08 10:22:07 霜降: 2017-10-23 13:26:40 九月小: 2017-10-20 03:12:00
立冬: 2017-11-07 13:37:47 小雪: 2017-11-22 11:04:36 十月大: 2017-11-18 19:42:05
**大雪: 2017-12-07 06:32:36 冬至: 2017-12-22 00:27:54** 11月大: 2017-12-18 14:30:16

paiYue(2018)
节气  手表时              中气  手表时              农历月  朔的手表时
**大雪: 2017-12-07 06:32:36 冬至: 2017-12-22 00:27:54** 12月大: 2018-01-17 10:17:13
小寒: 2018-01-05 17:48:44 大寒: 2018-01-20 11:09:01 正月小: 2018-02-16 05:05:21
立春: 2018-02-04 05:28:32 雨水: 2018-02-19 01:17:59 二月大: 2018-03-17 21:11:38
惊蛰: 2018-03-05 23:28:10 春分: 2018-03-21 00:15:22 三月小: 2018-04-16 09:57:08
清明: 2018-04-05 04:12:42 谷雨: 2018-04-20 11:12:26 四月大: 2018-05-15 19:47:52
立夏: 2018-05-05 21:25:14 小满: 2018-05-21 10:14:30 五月小: 2018-06-14 03:43:24
芒种: 2018-06-06 01:28:59 夏至: 2018-06-21 18:07:10 六月小: 2018-07-13 10:47:57
小暑: 2018-07-07 11:41:43 大暑: 2018-07-23 05:00:14 七月大: 2018-08-11 17:57:43
立秋: 2018-08-07 21:30:32 处暑: 2018-08-23 12:08:31 八月小: 2018-09-10 02:01:27
白露: 2018-09-08 00:29:40 秋分: 2018-09-23 09:54:06 九月大: 2018-10-09 11:46:54
寒露: 2018-10-08 16:14:42 霜降: 2018-10-23 19:22:16 十月小: 2018-11-08 00:02:04
立冬: 2018-11-07 19:31:33 小雪: 2018-11-22 17:01:13 11月大: 2018-12-07 15:20:10

**Comment by Comee** [comment]
不是bug，时间和次序上是没有问题的

![image](https://user-images.githubusercontent.com/5416227/28953270-82ba1f7e-7909-11e7-9087-229a0ae7fab9.png)

**Comment by yidao2015** [comment]
为什么同样的节气 后面跟的农历月不一样。
paiYue(2017)
大雪: 2017-12-07 06:32:36 冬至: 2017-12-22 00:27:54 **11月大: 2017-12-18 14:30:16**
paiYue(2018)
大雪: 2017-12-07 06:32:36 冬至: 2017-12-22 00:27:54 **12月大: 2018-01-17 10:17:13**

**Comment by Comee** [comment]
节气 中气是一组东西，
农历月是另外一组东西。
两者时间上没有必然联系。

**Comment by Comee** [comment]
你可以和你手机上的农历月对比下，是一致的。

**Comment by yidao2015** [comment]
以前以为农历月在节气的节之间的。
现在明白了。农历月的时间是对的。
